name: Deploy NodeJS Application to HomeServer

on:
  push:
    branches:
      - release/1.0
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with: 
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER_NAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /workspace/nodejs-application-delpoy-github-actions
            git pull 
            docker compose up -d --build
