name: Deploy to Home Server

on:
  push:
    branches:
      - release/1.0
      - master

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Connect to Tailscale
      uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:ci
    - name: Deploy to Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 100.125.217.85
        username: nadeem-gulam
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /workspace/nodejs-application-delpoy-github-actions
          git pull
          docker compose up -d --build